name: file handling test in GH Script

on:
  pull_request:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v2

      - name: open file properly
        uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
              const fs = require('fs')
              var issueBody = "Report file not found. Check pipeline for errors."
              try {
                  issueBody = fs.readFileSync("./src/reporting/dummy.md", "utf8")
                  const returnLabel = "completed"
              } catch (err) {
                  const returnLabel1 = "completed"
              }
              github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: issueBody
              })
              github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["test"]
              })
